# @see http://eslint.org/docs/2.0.0/user-guide/configuring

root: true

env:
    node: true

parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        spread: true
        experimentalObjectRestSpread: true

globals:
  module: false
  exports: true
  node: true
  browser: true
  $tw: true

rules:
    semi: 1 # require semicolons
    no-unused-vars: 1
    quotes: [ 1, 'single' ]
    indent: [ 1, 4 ] # 4-space indentation
    keyword-spacing: 1 # space before and after
    array-bracket-spacing: [1, 'always']  # enforce spaces inside of brackets
    no-unreachable: 2
    no-else-return: 1
    strict: 1
    no-shadow: 1
